### ISSUE TITLE
Stworzenie testów wydajnościowych/akceptacyjnych

### ISSUE THREAD

**Issue by PiotrJTomaszewski** [PiotrJTomaszewski/IO-Buildings#10]
Stworzenie testów wydajnościowych / akceptacyjnych.
Testy potrzebne dla:
- [x] #11 Implementacja REST API
- [x] #14 Łączna powierzchnia
- [x] #17 Łączna kubatura
- [x] #23 Moc oświetlenia
- [x] #27 Zużycie energii na ogrzewanie
- [x] #28 Próg zużycia energii
