### ISSUE TITLE
Implementacja REST API

### ISSUE THREAD

**Issue by PiotrJTomaszewski** [PiotrJTomaszewski/IO-Buildings#11]
## Element rejestru produktu
"Jako twórca oprogramowania do zarządzania budynkami mogę korzystać z dostępnych funkcji zdalnie poprzez REST, aby móc  zintegrować narzędzie z moimi innymi aplikacjami."

Ważność: 20
Pracochłonność: 3
Business Value: 1

## Zadania
(W nawiasach podana jest oszacowana pracochłonność)
 - [x] #5 Przetwarzanie danych na wejściu/wyjściu w formacie JSON. (0.5)
 - [x] #6 Stworzenie struktury, w której będziemy przechowywać dane na temat budynków. (1)
 - [x] #7 Implementacja REST API. (1.5)
 - [x] #8 Stworzenie dokumentacji. (?)
