### ISSUE TITLE
Łączna powierzchnia

### ISSUE THREAD

**Issue by PiotrJTomaszewski** [PiotrJTomaszewski/IO-Buildings#14]
## Element rejestru produktu
"Jako zarządca budynku mogę sprawdzić łączną powierzchnie budynku, poziomu lub pomieszczenia, aby móc prowadzić wyliczenia bazujące na powierzchni."

Ważność: 15
Pracochłonność: 3
Business Value: 1

## Zadania
(W nawiasach podana jest oszacowana pracochłonność)
 - [x] #12 Liczenie powierzchni dla poziomu. (1)
 - [x] #13 Liczenie powierzchni dla budynku. (1)
 - [x] #18 Liczenie powierzchni dla pomieszczenia. (1)
 - [x] #8 Stworzenie dokumentacji. (?)
