### ISSUE TITLE
Łączna kubatura

### ISSUE THREAD

**Issue by PiotrJTomaszewski** [PiotrJTomaszewski/IO-Buildings#17]
## Element rejestru produktu
"Jako zarządca budynku mogę sprawdzić łączną kubaturę pomieszczeń w budynku, na poziomu czy też pobrać kubaturę pomieszczenia, aby móc prowadzić wyliczenia bazujące na kubaturze pomieszczeń."

Ważność: 12
Pracochłonność: 3
Business Value: 1

## Zadania
(W nawiasach podana jest oszacowana pracochłonność)
 - [x] #15 Liczenie kubatury dla poziomu. (1)
 - [x] #16 Liczenie kubatury dla budynku. (1)
 - [x] #19 Liczenie kubatury dla pomieszczenia. (1)
 - [x] #8 Stworzenie dokumentacji. (?)
