### ISSUE TITLE
Moc oświetlenia

### ISSUE THREAD

**Issue by PiotrJTomaszewski** [PiotrJTomaszewski/IO-Buildings#23]
## Element rejestru produktu
"Jako zarządca budynku mogę obliczyć moc oświetlenia w przeliczeniu na jednostkę powierzchni dla budynku, poziomu, pomieszczenia."

Ważność: 10
Pracochłonność: 3
Business Value: 1

## Zadania
(W nawiasach podana jest oszacowana pracochłonność)
 - [x] #20 Liczenie mocy oświetlenia dla budynku. (1)
 - [x] #21 Liczenie mocy oświetlenia dla poziomu. (1)
 - [x] #22 Liczenie mocy oświetlenia dla pomieszczenia. (1)
 - [x] #8 Stworzenie dokumentacji. (?)
