### ISSUE TITLE
Zużycie energii na ogrzewanie

### ISSUE THREAD

**Issue by PiotrJTomaszewski** [PiotrJTomaszewski/IO-Buildings#27]
## Element rejestru produktu
"Jako zarządca budynku mogę obliczyć zużycie energii na ogrzewanie w przeliczeniu na jednostkę objętości dla budynku, poziomu, pomieszczenia."

Ważność: 10
Pracochłonność: 3
Business Value: 1

## Zadania
(W nawiasach podana jest oszacowana pracochłonność)
 - [x] #26 Liczenie zużycia energii dla budynku. (1)
 - [x] #25 Liczenie zużycia energii dla poziomu. (1)
 - [x] #24 Liczenie zużycia energii dla pomieszczenia. (1)
 - [x] #8 Stworzenie dokumentacji. (?)
