### ISSUE TITLE
Stworzenie dokumentacji

### ISSUE THREAD

**Issue by PiotrJTomaszewski** [PiotrJTomaszewski/IO-Buildings#8]
Stworzenie dokumentacji kodu.
Dokumentacja potrzebna dla:
- [x] #11 Implementacja REST API
- [x] #14 Łączna powierzchnia
- [x] #17 Łączna kubatura
- [x] #23 Moc oświetlenia
- [x] #27 Zużycie energii na ogrzewanie
- [x] #28 Próg zużycia energii

**Comment by PiotrJTomaszewski** [comment]
Odnośnie dokumentacji z zasad punktowania sprintu: 
"Pełna dokumentacja techniczna: opis przeznaczenia **klasy / interfejsu**; opis wszystkich **metod** (innych niż get / set); opis przeznaczenia **pól**"
